CREATE TABLE IF NOT EXISTS teacher
(
    `id`   BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(30) NULL DEFAULT NULL,
    age    INT         NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS student
(
    `id`   BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(30) NULL DEFAULT NULL,
    age    INT         NULL DEFAULT NULL
);
